name: mlflow-8118c03ea5d3622a9010ba95aa9d5a144de06016
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - chardet=3.0.4=py_1
  - idna=2.10=pyh9f0ad1d_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgomp=11.2.0=h1d223b6_12
  - libnsl=2.0.0=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.11=h36c2ea0_1013
  - ncurses=6.3=h9c3ff4c_0
  - openssl=1.1.1l=h7f98852_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - python=3.10.2=h85951f9_3_cpython
  - python_abi=3.10=2_cp310
  - readline=8.1=h46c0cb4_0
  - requests=2.24.0=pyh9f0ad1d_0
  - sqlite=3.37.0=h9cd32fc_0
  - tk=8.6.11=h27826a3_1
  - tzdata=2021e=he74cb21_0
  - urllib3=1.25.11=py_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h36c2ea0_1013
  - pip:
    - brotlipy==0.7.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - click==8.0.3
    - configparser==5.2.0
    - cryptography==36.0.1
    - docker-pycreds==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.26
    - kaggle==1.5.12
    - opendatasets==0.1.20
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.0
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-slugify==5.0.2
    - pyyaml==6.0
    - sentry-sdk==1.5.5
    - setuptools==60.9.0
    - shortuuid==1.0.8
    - six==1.16.0
    - smmap==5.0.0
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - text-unidecode==1.3
    - tqdm==4.62.3
    - wandb==0.12.9
    - yaspin==2.1.0
prefix: /home/mariana/anaconda3/envs/mlflow-8118c03ea5d3622a9010ba95aa9d5a144de06016
