name: mlflow-521646bdb8ef773b1f4c4ec0a73df68c0c121729
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alembic=1.4.1=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asn1crypto=1.4.0=pyh9f0ad1d_0
  - brotlipy=0.7.0=py38h497a2fe_1003
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py38h578d9bd_1
  - cffi=1.15.0=py38h3931269_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.0.3=py38h578d9bd_1
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - configparser=5.2.0=pyhd8ed1ab_0
  - cryptography=36.0.1=py38h3e25421_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - databricks-cli=0.12.1=pyhd8ed1ab_0
  - docker-py=5.0.3=py38h578d9bd_2
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - flask=2.0.3=pyhd8ed1ab_0
  - freetype=2.10.4=h0708190_1
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.26=pyhd8ed1ab_0
  - greenlet=1.1.2=py38h709712a_1
  - gunicorn=20.1.0=py38h578d9bd_1
  - icu=67.1=he1b5a44_0
  - idna=3.3=pyhd8ed1ab_0
  - itsdangerous=2.0.1=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h7f98852_0
  - kiwisolver=1.3.2=py38h1fd1430_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_openblas
  - libcblas=3.9.0=13_linux64_openblas
  - libdeflate=1.10=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libgomp=11.2.0=h1d223b6_12
  - liblapack=3.9.0=13_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.19.4=h780b84a_0
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libtiff=4.3.0=h542a066_3
  - libwebp-base=1.2.2=h7f98852_1
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h9c3ff4c_1
  - mako=1.1.6=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38h497a2fe_1
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py38h5d868c9_1
  - ncurses=6.3=h9c3ff4c_0
  - numpy=1.22.2=py38h6ae9a64_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py38h43a58ef_0
  - pillow=8.4.0=py38h8e6f84c_0
  - pip=21.3.1=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.18.7=pyhd8ed1ab_0
  - protobuf=3.19.4=py38h709712a_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h578d9bd_4
  - python=3.8.12=ha38a3c6_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd8ed1ab_0
  - pyyaml=6.0=py38h497a2fe_3
  - querystring_parser=1.2.4=py_0
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py38h1561384_0
  - scipy=1.8.0=py38h56a6a73_1
  - setuptools=59.8.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlalchemy=1.4.31=py38h497a2fe_0
  - sqlite=3.37.0=h9cd32fc_0
  - sqlparse=0.4.2=pyhd8ed1ab_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tenacity=8.0.1=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - tornado=6.1=py38h497a2fe_2
  - typing_extensions=4.1.1=pyha770c72_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - websocket-client=1.2.3=pyhd8ed1ab_0
  - werkzeug=2.0.3=pyhd8ed1ab_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - antlr4-python3-runtime==4.8
    - mlflow==1.14.1
    - omegaconf==2.1.1
    - pathtools==0.1.2
    - promise==2.3
    - psutil==5.9.0
    - sentry-sdk==1.5.5
    - shortuuid==1.0.8
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - wandb==0.12.9
    - yaspin==2.1.0
prefix: /home/mariana/anaconda3/envs/mlflow-521646bdb8ef773b1f4c4ec0a73df68c0c121729
